project:
  type: website

website:
  title: "Valeria Fierros"
  navbar:
    left:
       - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Projects.qmd
        text: Projects
      - href: reading.qmd
        text: Reading
      - href: resume.qmd
        text: Resume

format:
  html:
    theme:
      - quartz
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

