project:
  type: website
  output-dir: docs

website:
  title: "Valeria Fierros"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Projects.qmd
      - reading.qmd
      - resume.qmd

format:
  html:
    theme:
      - quartz
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

